"""Added a latitude and longitude column to the address table

Revision ID: 2a550fd8df56
Revises: 74e879d7fd2e
Create Date: 2022-03-26 03:15:57.469429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a550fd8df56'
down_revision = '74e879d7fd2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('address', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('address', 'longitude')
    op.drop_column('address', 'latitude')
    # ### end Alembic commands ###
