"""Notifications changes

Revision ID: 45419ad8fc23
Revises: 2a550fd8df56
Create Date: 2022-04-04 16:07:49.997405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45419ad8fc23'
down_revision = '2a550fd8df56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('message', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification', 'message')
    # ### end Alembic commands ###
