"""added a borrow history model to the database

Revision ID: 509182f49149
Revises: 45419ad8fc23
Create Date: 2022-04-06 16:24:43.813518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '509182f49149'
down_revision = '45419ad8fc23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('borrow_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tool_id', sa.Integer(), nullable=False),
    sa.Column('deposit_paid', sa.Integer(), nullable=False),
    sa.Column('active_status', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('borrow_history')
    # ### end Alembic commands ###
