"""Removed the location column from the tools table, as the location will be saved in the address table

Revision ID: 74e879d7fd2e
Revises: 5fe194e70db4
Create Date: 2022-03-19 03:46:44.647501

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '74e879d7fd2e'
down_revision = '5fe194e70db4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tools', 'location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tools', sa.Column('location', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=25), nullable=False))
    # ### end Alembic commands ###
