"""empty message

Revision ID: b3b1e7cd5e25
Revises: 509182f49149
Create Date: 2022-04-06 17:01:39.695509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3b1e7cd5e25'
down_revision = '509182f49149'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('borrow_history', sa.Column('date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('borrow_history', 'date')
    # ### end Alembic commands ###
