"""changed the database model of the img, user and tool class

Revision ID: e50bb4b8faf6
Revises: 6f12a8fe264f
Create Date: 2022-03-07 19:22:11.118065

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e50bb4b8faf6'
down_revision = '6f12a8fe264f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('img', sa.Column('tool_id', sa.Integer(), nullable=True))
    op.add_column('img', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'img', 'tools', ['tool_id'], ['id'])
    op.create_foreign_key(None, 'img', 'user', ['user_id'], ['id'])
    op.drop_constraint('tools_ibfk_2', 'tools', type_='foreignkey')
    op.drop_column('tools', 'image_id')
    op.drop_constraint('user_ibfk_1', 'user', type_='foreignkey')
    op.drop_column('user', 'image_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('image_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('user_ibfk_1', 'user', 'img', ['image_id'], ['id'])
    op.add_column('tools', sa.Column('image_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('tools_ibfk_2', 'tools', 'img', ['image_id'], ['id'])
    op.drop_constraint(None, 'img', type_='foreignkey')
    op.drop_constraint(None, 'img', type_='foreignkey')
    op.drop_column('img', 'user_id')
    op.drop_column('img', 'tool_id')
    # ### end Alembic commands ###
