"""Made an image table to hold all images, and added a reference to the image in tools and user

Revision ID: f1eca4575b38
Revises: cec2ff0f1c73
Create Date: 2022-02-25 23:43:35.627209

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f1eca4575b38'
down_revision = 'cec2ff0f1c73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tools', sa.Column('image_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tools', 'img', ['image_id'], ['id'])
    op.drop_column('tools', 'image_file')
    op.drop_column('tools', 'image')
    op.add_column('user', sa.Column('image_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'img', ['image_id'], ['id'])
    op.drop_column('user', 'image_file')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('image_file', mysql.VARCHAR(length=40), nullable=False))
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'image_id')
    op.add_column('tools', sa.Column('image', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('tools', sa.Column('image_file', mysql.VARCHAR(length=40), nullable=False))
    op.drop_constraint(None, 'tools', type_='foreignkey')
    op.drop_column('tools', 'image_id')
    # ### end Alembic commands ###
